### ISSUE TITLE
deduper psuedo feedback

### ISSUE THREAD

**Issue by leycufur** [rlancaster96/Deduper-rlancaster96#1]
- Very nice and thorough pseudocode! Much better than mine anyway. 
- looks like you are going to avoid loading everything into memory, adjust for soft clipping, and account for reverse complements
- for using samtools, you can sort by read names and it might be easier/faster that way to identify duplicates
- I could be wrong... but I think we need to include all the "@" lines (header section) in the SAM output. 
- I remember making a reverse complement function for a past assignment that we have in our bioinfo.py so you can probably use that if you weren't already planning to. EDIT: after looking at some other pseduocode, I don't think you would need to do reverse complements. I saw Bailey already mentioned a way to do it and you can get more ideas from looking at other pseudocodes

**Comment by rlancaster96** [comment]
Thanks Leyla!
- Added writing header lines to output 
- Removed reverse complementing
