### ISSUE TITLE
Psuedocode feedback

### ISSUE THREAD

**Issue by bayknight** [rlancaster96/Deduper-rlancaster96#2]
Overall the logic makes sense and its easy to follow.
Im curious if reverse complementing is needed or if the sequence position can be shifted to the right using the cigar string instead. I think we will have more clarity on this tomorrow in class.
I like your use of a set rather than a dictionary. 
The functions you have will be nice as well.
 I think you are supposed to store the @lines to your output files first.
 Overall nice job. It seems to do what its supposed to do and the functions are reasonable.

**Comment by rlancaster96** [comment]
Thanks Bailey!
- reverse complement removed in final code, you're right it's not necessary
- added writing out header lines to file
