### ISSUE TITLE
Deduper Pseudocode Review

### ISSUE THREAD

**Issue by emybart415** [rlancaster96/Deduper-rlancaster96#3]
I like the way you begin each section with its own little behind the scenes thought process blurb, makes it easy to follow as a reader.
•	You are the first code I have read that reverse compliments the UMI based on strandedness! I have this in my code, but after reading more comments and pseudocode it may or may not be necessary?
•	Your preprocessing, sorting out unmapped and secondary alignments, is quite smart.
•	You may need to be tallying removed duplicates, we will probably need to do some data output on how many were removed.
•	I would mention you don’t seem to write the header lines to the final file, but the first reviewers caught that already.

**Comment by rlancaster96** [comment]
Thanks Emily! 
- Added tally for removed duplicates
- No longer considering reverse complements 
- Added writing header lines to final file
